services:
  bikeradar:
    container_name: bikeradar
    network_mode: host
    build: .
    volumes:
      - .:/app
    entrypoint:
       - uvicorn
       - --reload
       - --factory
       - --port
       - "8000"
       - bikeradar.main:run
    environment:
      - GBFS_BASE_URL=https://gbfs.urbansharing.com/oslobysykkel.no/gbfs.json
      - GBFS_LANGUAGE=nb

